### ISSUE TITLE
Unable to draw the solar array a second time

### ISSUE THREAD

**Issue by andywalz** [respec/solar-suitability-app#61]
After saving, returning to report, and then back to draw panels the tool lets you draw but the feature doesn't stick/save.

**Comment by cmartin616** [comment]
This should be fixed in cmDrawFix.  Please test on your machine.

**Comment by andywalz** [comment]
I'm now able to draw a second time but the red clear button didn't work at all for me.

**Comment by cmartin616** [comment]
Oh you are right.  I didn't update that.  Oops!  I'll get it soon.
