### ISSUE TITLE
Unexpected results from Solar Calculator

### ISSUE THREAD

**Issue by andywalz** [respec/solar-suitability-app#69]
Chris- Can you look into this when you get time? Thx.

[solarmapapp.pdf](https://github.com/flatrockgeo/solar-suitability-app/files/73362/solarmapapp.pdf)

**Comment by cmartin616** [comment]
Hey, I started to look into it.

Values look good:

https://docs.google.com/spreadsheets/d/1vZEGpm2rzhNYmGI1sTZM62I2rus5E4EV3GqS8Pl8k9I/edit#gid=0

I'm going to look into how it is displayed.  I can't recreate the specific points Dan referenced without lat/lng with 10 digit scale (x.0123456789).  I've grabbed some local ones and see data that makes sense.  I'll try to trip up the display and double check the logic.
