### ISSUE TITLE
App gets "stuck" when ImageService unavailable

### ISSUE THREAD

**Issue by andywalz** [respec/solar-suitability-app#74]
Is there an easy way we could make the app fail gracefully when ArcGIS server is down (i.e. Solar ImageService not available)? Handle no or error response and showalert “Solar data temporarily unavailable, please check back soon…”

Currently it just sticks on “Calculating…"

**Comment by cmartin616** [comment]
It's actually failing on the queries.  I have added error callbacks but they need to be updated to send an email to our email.  It appears to be working in cmFailGracefully but the services came back up before fully testing.  You will see it in the serverError function.  I haven't been able to test the failed ImageServiceLayer but I built in an error listener.
